name: my_hotel_booking_app
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  flutter_riverpod: ^2.1.3
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  pin_code_fields: ^7.3.0
  smooth_page_indicator: ^1.0.0+2
  grouped_list: ^5.1.2
  google_maps_flutter: ^2.0.0
  table_calendar: ^3.0.6
  flutter_svg_provider: ^1.0.3
  qr_flutter: ^4.1.0
  intl: ^0.18.0
  url_launcher: 6.0.20
  firebase_core: ^2.21.0
  firebase_auth: ^4.12.1
  google_sign_in: ^6.1.5
  rating_dialog: ^2.0.4
  flutter_spinkit: ^5.2.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Urbanist
      fonts: 
        - asset: assets/fonts/UrbanistRomanBold.ttf
          weight: 700
        - asset: assets/fonts/UrbanistRomanBlack.ttf
          weight: 900
        - asset: assets/fonts/UrbanistSemiBold.ttf
          weight: 600
        - asset: assets/fonts/UrbanistRegular.ttf
          weight: 400
        - asset: assets/fonts/UrbanistRomanMedium.ttf
          weight: 500
